services:
  - type: web
    name: InvestPro
    runtime: php
    rootDir: backend
    plan: free
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://investpro-backend.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_DATABASE
        fromDatabase:
          name: investpro-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: investpro-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: investpro-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: investpro-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: investpro-db
          property: port
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: SANCTUM_STATEFUL_DOMAINS
        value: investpro-app.netlify.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://investpro-app.netlify.app
      - key: MAIL_MAILER
        value: log

databases:
  - name: investpro-db
    plan: free
    databaseName: investpro
